### ISSUE TITLE
Add hex color support for node specific colorize.

### ISSUE THREAD

**Issue by mumincelal** [mumincelal/ngx-org-chart#29]

**Comment by sai-github** [comment]
Is it possible to add two css classes ?

**Comment by MuminCelal** [comment]
What do you mean about "Is it possible to add two css classes?" @sai-github ?

**Comment by sai-github** [comment]
As we are mentioning css class name inside `.ts` file, I thought modifying the `cssClass: 'ngx-org-ceo'` prop would add new css styles. If this is possible it would be interesting to assign `cssClass` an array of string (ex: `cssClass: ['ngx-org-ceo', 'ngx-org-assitant']`)

I have a specific example in my mind, let say when the user hovers on the leaf node, we would like to highlight all the node till root (may be to show the hierarchy from leaf till root) I want to add a new css styles to these nodes, maybe something like border/shadow

**Comment by mumincelal** [comment]
I work on v2.0 and I plan to publish it unstyled so custom styling will be supported.
