### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by lauramgran** [MuminCelal/ngx-org-chart#57]
I am trying to update my website to angular 10, but apparently this component is not compatible with that version.

![Captura de pantalla de 2020-11-17 13-22-47](https://user-images.githubusercontent.com/74601976/99389891-06610280-28d8-11eb-953a-17ed4a087f07.png)

**Comment by MuminCelal** [comment]
Hi @lauramgran,

The current package is compatible with Angular 8 for now. I will update the package to Angular 11. I am working on it for now and I push the new version of it till this weekend.

You can use the package after the new version released with Angular 10 and 11.

**Comment by lauramgran** [comment]
Its already updated?

**Comment by MuminCelal** [comment]
The update will come tomorrow.

**Comment by lauramgran** [comment]
I have already been able to update the component, thank you very much!!
