### ISSUE TITLE
Custom Designs for Connectors

### ISSUE THREAD

**Issue by jpierresamra** [mumincelal/ngx-org-chart#66]
Connectors are currently a line connecting 2 entities. 
It would be great to have different styles of connectors (arrow heads, bullet heads, et.) this way a flow chart can look better with arrow headed connectors, can be from one side or both sides. 
Also, it would be nice to add css customization to the connectors themselves, for example their color and thickness. This might be useful if we want to emphasis on a certain connection importance for example.

**Comment by mumincelal** [comment]
I work on v2.0 and I will try to implement this one.
