### ISSUE TITLE
Is there any way to create custom template for each node?

### ISSUE THREAD

**Issue by Virendraccc** [mumincelal/ngx-org-chart#71]
![image](https://user-images.githubusercontent.com/122018749/212004547-ec6178d4-fe98-4474-aff0-99df5b7427ef.png)

**Comment by mumincelal** [comment]
I am planning to deploy new version and this will be included 2 weeks later I will be planning to deploy new version

**Comment by mumincelal** [comment]
I work on v2.0 and I will try to implement this one but not short term
