### ISSUE TITLE
Not compatible with Ivy

### ISSUE THREAD

**Issue by jeanRandria** [mumincelal/ngx-org-chart#72]
'NgxOrgChartModule' does not appear to be an NgModule class.

This likely means that the library (ngx-org-chart) which declares NgxOrgChartModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with I

**Comment by DhivyaDelphina** [comment]
Yes, Even I'm also facing this issue. Could you please provide the resolution soon.

**Comment by mumincelal** [comment]
Hi,

I will fix it as soon as possible. Thank you.

**Comment by LomeshBadhe** [comment]
@mumincelal i am still facing the same error. when should I expect the fixed ?

**Comment by PandeyRishiV** [comment]
Hi @mumincelal any update on this issue?

**Comment by fdjlss** [comment]
> Hi @mumincelal any update on this issue?

I've forked the project and published an Ivy-compatible version of ngx-org-chart (plus supports innerHTML for `title` and `name` node fields). 
https://www.npmjs.com/package/@fdjlss/ngx-org-chart?activeTab=versions
Ver. 1.0.8 should be fully functional. If not, then super sorry for wasting your time ＞﹏＜

**Comment by mumincelal** [comment]
Hi, I am busy these days with other projects. I am planning to start working next week. The new version will come with a bunch of features.

**Comment by mumincelal** [comment]
I work on v2.0 and this will be supported
